project:
  type: website

website:
  title: Yiluan Song
  favicon: otter.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
